package sistemaBiblioteca;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


/**
 *
 * @author marci
 */

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class CadastrarLivro extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public CadastrarLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeLivro = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Autor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAlterarLivro = new javax.swing.JButton();
        btnListarLivro = new javax.swing.JButton();
        txtAutor = new javax.swing.JTextField();
        btnCadastrarLivro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLivro = new javax.swing.JTable();
        txtEditora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEdicao = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Cadastro de Livros");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Dados")));

        jLabel3.setText("Nome do Livro");

        jLabel4.setText("Gênero");

        Autor.setText("Autor");

        jLabel7.setText("Edição");

        jLabel8.setText("Quantidade");

        btnAlterarLivro.setText("Alterar");
        btnAlterarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarLivroActionPerformed(evt);
            }
        });

        btnListarLivro.setText("Listar");
        btnListarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLivroActionPerformed(evt);
            }
        });

        btnCadastrarLivro.setText("Cadastrar");
        btnCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarLivroActionPerformed(evt);
            }
        });

        tbLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Idade", "Email", "Telefone", "Situacao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLivroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLivro);

        jLabel6.setText("Editora");

        jLabel5.setText("ISBN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(txtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(25, 25, 25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEditora)
                                .addComponent(txtEdicao)
                                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Autor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarLivro)
                    .addComponent(btnAlterarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarLivro))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarLivro)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterarLivro)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Autor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(591, 591, 591))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
private void alterarLivro() {
   
    try {
        // Verifica se uma linha foi selecionada na tabela
        int selectedRow = tbLivro.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um livro na tabela para alterar.");
            return;
        }

        // Obtém o ID do livro da tabela (coluna 0)
        int idLivro = (int) tbLivro.getValueAt(selectedRow, 0);

        // Recupera os valores dos campos de entrada (TextFields)
        String nome = txtNomeLivro.getText();
        String genero = txtGenero.getText();
        String autor = txtAutor.getText();
        String editora = txtEditora.getText();
        String edicao = txtEdicao.getText();
        String quantidadeText = txtQuantidade.getText();
        String isbn = txtISBN.getText();

        // Validação simples para evitar valores vazios
        if (nome.isEmpty() || genero.isEmpty() || autor.isEmpty() || editora.isEmpty() || edicao.isEmpty() || quantidadeText.isEmpty() || isbn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!");
            return;
        }

        // Converte a quantidade para inteiro
        int quantidade;
        try {
            quantidade = Integer.parseInt(quantidadeText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Quantidade deve ser um número válido.");
            return;
        }

        // Conexão com o banco de dados
        java.sql.Connection con = Conexao.conexaoBanco();

        // SQL para verificar se o ISBN já existe para outro livro
        String sqlCheckISBN = "SELECT * FROM livro WHERE ISBN = ? AND id_livro != ?";
        PreparedStatement stmtCheckISBN = con.prepareStatement(sqlCheckISBN);
        stmtCheckISBN.setString(1, isbn);
        stmtCheckISBN.setInt(2, idLivro); // Verifica se o ISBN já existe, mas não para o próprio livro
        ResultSet rs = stmtCheckISBN.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(null, "O ISBN já está cadastrado para outro livro.");
        } else {
            // SQL para atualizar o livro
            String sqlUpdate = "UPDATE livro SET nome = ?, genero = ?, autor = ?, editora = ?, edicao = ?, quantidade = ?, ISBN = ? WHERE id_livro = ?";
            PreparedStatement stmtUpdate = con.prepareStatement(sqlUpdate);
            stmtUpdate.setString(1, nome);
            stmtUpdate.setString(2, genero);
            stmtUpdate.setString(3, autor);
            stmtUpdate.setString(4, editora);
            stmtUpdate.setString(5, edicao);
            stmtUpdate.setInt(6, quantidade);
            stmtUpdate.setString(7, isbn);  // Altera o ISBN
            stmtUpdate.setInt(8, idLivro);  // Atualiza o livro com o ID informado

            // Executa a atualização
            int rowsUpdated = stmtUpdate.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Livro alterado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum livro foi alterado.");
            }

            stmtUpdate.close();
        }

        rs.close();
        stmtCheckISBN.close();
        con.close();

        // Atualiza a tabela (chame seu método de listar livros aqui)
        listarLivros(); // Método para atualizar a tabela de livros

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Erro ao alterar livro: " + ex.getMessage());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Erro: Verifique se os campos de quantidade e valores numéricos estão corretos.");
    }
}


    
   private void listarLivros() {
    try {
        // Conexão com o banco de dados
        java.sql.Connection con = Conexao.conexaoBanco();

        // Consulta SQL para selecionar todos os livros
        String sql = "SELECT * FROM livro";
        PreparedStatement stmt = con.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();

        // Obtém o modelo da tabela
        DefaultTableModel model = (DefaultTableModel) tbLivro.getModel();

        // Limpa os dados existentes na tabela
        model.setRowCount(0);

        // Adiciona os registros ao modelo da tabela
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_livro"),           // ID do livro
                rs.getString("nome"),      // Nome do livro
                rs.getString("genero"),    // Gênero do livro
                rs.getString("autor"),     // Autor do livro
                rs.getString("editora"),   // Editora do livro
                rs.getString("edicao"),    // Edição do livro
                rs.getInt("quantidade"),   // Quantidade de livros
                rs.getString("ISBN")       // ISBN do livro
            });
        }

        // Fecha os recursos
        rs.close();
        stmt.close();
        con.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Erro ao listar livros: " + ex.getMessage());
    }
}


    
    
    private void btnAlterarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarLivroActionPerformed
       alterarLivro();
    }//GEN-LAST:event_btnAlterarLivroActionPerformed

    private void btnListarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLivroActionPerformed
        listarLivros();
    }//GEN-LAST:event_btnListarLivroActionPerformed

    private void btnCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLivroActionPerformed
        try {
        String nome = txtNomeLivro.getText();
        String genero = txtGenero.getText();
        String autor = txtAutor.getText();
        String editora = txtEditora.getText();
        String edicao = txtEdicao.getText();
        int quantidade = Integer.parseInt(txtQuantidade.getText());
        String isbn = txtISBN.getText();  // Vamos adicionar o campo ISBN

        // Verifica se o ISBN já existe
        java.sql.Connection con = Conexao.conexaoBanco();
        String sqlCheckISBN = "SELECT * FROM livro WHERE ISBN = ?";
        PreparedStatement stmtCheckISBN = con.prepareStatement(sqlCheckISBN);
        stmtCheckISBN.setString(1, isbn);
        ResultSet rs = stmtCheckISBN.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(null, "O ISBN já está cadastrado.");
        } else {
            // Se não existir, insere o novo livro
            String sqlInsert = "INSERT INTO livro (nome, genero, autor, editora, edicao, quantidade, ISBN) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement stmtInsert = con.prepareStatement(sqlInsert);
            stmtInsert.setString(1, nome);
            stmtInsert.setString(2, genero);
            stmtInsert.setString(3, autor);
            stmtInsert.setString(4, editora);
            stmtInsert.setString(5, edicao);
            stmtInsert.setInt(6, quantidade);
            stmtInsert.setString(7, isbn);  // Insere o ISBN

            stmtInsert.executeUpdate();
            JOptionPane.showMessageDialog(null, "Livro cadastrado com sucesso!");
        }

        rs.close();
        stmtCheckISBN.close();
        con.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Erro ao cadastrar livro: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnCadastrarLivroActionPerformed

    private void tbLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLivroMouseClicked
        // TODO add your handling code here:

        int row = tbLivro.getSelectedRow();
        if (row != -1) {
        txtNomeLivro.setText(tbLivro.getValueAt(row, 1).toString());
        txtAutor.setText(tbLivro.getValueAt(row, 2).toString());
        txtGenero.setText(tbLivro.getValueAt(row, 3).toString());
        txtEdicao.setText(tbLivro.getValueAt(row, 4).toString());
        txtEditora.setText(tbLivro.getValueAt(row, 5).toString());
        txtQuantidade.setText(tbLivro.getValueAt(row, 6).toString());
    }
    }//GEN-LAST:event_tbLivroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autor;
    private javax.swing.JButton btnAlterarLivro;
    private javax.swing.JButton btnCadastrarLivro;
    private javax.swing.JButton btnListarLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLivro;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEdicao;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNomeLivro;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
