package sistemaBiblioteca;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author marci
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastrarUsuarioHome = new javax.swing.JButton();
        btnEmprestimoHome = new javax.swing.JButton();
        btnCadastrarLivroHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDevolucaoHome = new javax.swing.JButton();
        btnPesquisarHome = new javax.swing.JButton();
        btnSairHome = new javax.swing.JButton();
        PainelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnCadastrarUsuarioHome.setBackground(new java.awt.Color(204, 255, 255));
        btnCadastrarUsuarioHome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadastrarUsuarioHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente-removebg-preview.png"))); // NOI18N
        btnCadastrarUsuarioHome.setText("Cadastrar Usuário");
        btnCadastrarUsuarioHome.setHideActionText(true);
        btnCadastrarUsuarioHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarUsuarioHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastrarUsuarioHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuarioHomeActionPerformed(evt);
            }
        });

        btnEmprestimoHome.setBackground(new java.awt.Color(204, 255, 255));
        btnEmprestimoHome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEmprestimoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/emprestimo.png"))); // NOI18N
        btnEmprestimoHome.setText("Empréstimo");
        btnEmprestimoHome.setToolTipText("");
        btnEmprestimoHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEmprestimoHome.setBorderPainted(false);
        btnEmprestimoHome.setHideActionText(true);
        btnEmprestimoHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmprestimoHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmprestimoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoHomeActionPerformed(evt);
            }
        });

        btnCadastrarLivroHome.setBackground(new java.awt.Color(204, 255, 255));
        btnCadastrarLivroHome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadastrarLivroHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LivroAdicionar-removebg-preview.png"))); // NOI18N
        btnCadastrarLivroHome.setText("Cadastrar Livro");
        btnCadastrarLivroHome.setHideActionText(true);
        btnCadastrarLivroHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarLivroHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastrarLivroHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarLivroHomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("MENU");

        btnDevolucaoHome.setBackground(new java.awt.Color(204, 255, 255));
        btnDevolucaoHome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDevolucaoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Livro.png"))); // NOI18N
        btnDevolucaoHome.setText("Devolução");
        btnDevolucaoHome.setHideActionText(true);
        btnDevolucaoHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDevolucaoHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDevolucaoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucaoHomeActionPerformed(evt);
            }
        });

        btnPesquisarHome.setBackground(new java.awt.Color(204, 255, 255));
        btnPesquisarHome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPesquisarHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar-removebg-preview.png"))); // NOI18N
        btnPesquisarHome.setText("Pesquisar");
        btnPesquisarHome.setHideActionText(true);
        btnPesquisarHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisarHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisarHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarHomeActionPerformed(evt);
            }
        });

        btnSairHome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSairHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SAIR-removebg-preview.png"))); // NOI18N
        btnSairHome.setText("SAIR");
        btnSairHome.setHideActionText(true);
        btnSairHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSairHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSairHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEmprestimoHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastrarUsuarioHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastrarLivroHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDevolucaoHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisarHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnSairHome, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmprestimoHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDevolucaoHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarUsuarioHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarLivroHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairHome)
                .addContainerGap())
        );

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1156, Short.MAX_VALUE)
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarUsuarioHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioHomeActionPerformed
        // TODO add your handling code here:
       // Remove todos os componentes do PainelPrincipal (caso necessário)
    PainelPrincipal.removeAll();

    // Cria ou instancia o painel que será exibido
    CadastrarCliente2 l = new CadastrarCliente2();

    // Define um layout no PainelPrincipal se ainda não tiver (exemplo: BorderLayout)
    PainelPrincipal.setLayout(new java.awt.BorderLayout());

    // Adiciona o novo painel ao PainelPrincipal
    PainelPrincipal.add(l, java.awt.BorderLayout.CENTER);

    // Atualiza a interface para mostrar o novo painel
    PainelPrincipal.revalidate();
    PainelPrincipal.repaint();
        
    }//GEN-LAST:event_btnCadastrarUsuarioHomeActionPerformed

    private void btnDevolucaoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucaoHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDevolucaoHomeActionPerformed

    private void btnEmprestimoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoHomeActionPerformed
        // TODO add your handling code here:
        
           
         PainelPrincipal.removeAll();

    // Cria ou instancia o painel que será exibido
    Emprestimo l = new Emprestimo();

    // Define um layout no PainelPrincipal se ainda não tiver (exemplo: BorderLayout)
    PainelPrincipal.setLayout(new java.awt.BorderLayout());

    // Adiciona o novo painel ao PainelPrincipal
    PainelPrincipal.add(l, java.awt.BorderLayout.CENTER);

    // Atualiza a interface para mostrar o novo painel
    PainelPrincipal.revalidate();
    PainelPrincipal.repaint();
    }//GEN-LAST:event_btnEmprestimoHomeActionPerformed

    private void btnCadastrarLivroHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLivroHomeActionPerformed
        // TODO add your handling code here:
        
         PainelPrincipal.removeAll();

    // Cria ou instancia o painel que será exibido
    CadastrarLivro l = new CadastrarLivro();

    // Define um layout no PainelPrincipal se ainda não tiver (exemplo: BorderLayout)
    PainelPrincipal.setLayout(new java.awt.BorderLayout());

    // Adiciona o novo painel ao PainelPrincipal
    PainelPrincipal.add(l, java.awt.BorderLayout.CENTER);

    // Atualiza a interface para mostrar o novo painel
    PainelPrincipal.revalidate();
    PainelPrincipal.repaint();
    }//GEN-LAST:event_btnCadastrarLivroHomeActionPerformed

    private void btnSairHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairHomeActionPerformed

    private void btnPesquisarHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JButton btnCadastrarLivroHome;
    private javax.swing.JButton btnCadastrarUsuarioHome;
    private javax.swing.JButton btnDevolucaoHome;
    private javax.swing.JButton btnEmprestimoHome;
    private javax.swing.JButton btnPesquisarHome;
    private javax.swing.JButton btnSairHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
